ALTER TABLE cdss ADD COLUMN refseq_id INTEGER DEFAULT NULL;
ALTER TABLE cdss ADD COLUMN gk INTEGER DEFAULT 0;
ALTER TABLE cdss ADD COLUMN fk INTEGER DEFAULT 0;

ALTER TABLE scaffolds ADD COLUMN cds_count INTEGER;
ALTER TABLE scaffolds ADD COLUMN gk_count INTEGER;
ALTER TABLE scaffolds ADD COLUMN fk_count INTEGER;

ALTER TABLE genomes ADD COLUMN cds_count INTEGER;
ALTER TABLE genomes ADD COLUMN gk_count INTEGER;
ALTER TABLE genomes ADD COLUMN fk_count INTEGER;

ALTER TABLE clusters ADD COLUMN cds_count INTEGER;
ALTER TABLE clusters ADD COLUMN gk_count INTEGER;
ALTER TABLE clusters ADD COLUMN fk_count INTEGER;
